// lookup-ids.mjs — comprehensive lookup for all remaining bad IDs
// Run from your project root: node lookup-ids.mjs
// Requires TMDB_READ_ACCESS_TOKEN in your .env.local

import { readFileSync } from 'fs';
import { join } from 'path';

const envPath = join(process.cwd(), '.env.local');
const envVars = readFileSync(envPath, 'utf8');
const tokenMatch = envVars.match(/TMDB_READ_ACCESS_TOKEN=(.+)/);
const TOKEN = tokenMatch?.[1]?.trim();

if (!TOKEN) {
  console.error('TMDB_READ_ACCESS_TOKEN not found in .env.local');
  process.exit(1);
}

// FORMAT: ['Title to search', year, 'Label for output']
// Label helps us map results back to the right entry
const films = [
  // ── '90s Romance ────────────────────────────────────────────────────────────
  ['10 Things I Hate About You',           1999, 'ROMANCE|10 Things I Hate About You'],
  ['Basic Instinct',                        1992, 'ROMANCE|Basic Instinct'],
  ['Jerry Maguire',                         1996, 'ROMANCE|Jerry Maguire'],
  ['Before Sunrise',                        1995, 'ROMANCE|Before Sunrise'],
  ['The Wedding Singer',                    1998, 'ROMANCE|The Wedding Singer'],
  ['Practical Magic',                       1998, 'ROMANCE|Practical Magic'],
  ['Romeo + Juliet',                        1996, 'ROMANCE|Romeo + Juliet'],
  ['Mallrats',                              1995, 'ROMANCE|Mallrats'],
  ['Ghost',                                 1990, 'ROMANCE|Ghost'],
  ['Bicentennial Man',                      1999, 'ROMANCE|Bicentennial Man'],
  ['Hercules',                              1997, 'ROMANCE|Hercules'],
  ['Notting Hill',                          1999, 'ROMANCE|Notting Hill'],
  ['True Romance',                          1993, 'ROMANCE|True Romance'],
  ['Legends of the Fall',                   1994, 'ROMANCE|Legends of the Fall'],
  ['Cruel Intentions',                      1999, 'ROMANCE|Cruel Intentions'],
  ["There's Something About Mary",          1998, "ROMANCE|There's Something About Mary"],
  ['Sense and Sensibility',                 1995, 'ROMANCE|Sense and Sensibility'],
  ["Bram Stoker's Dracula",                 1992, 'ROMANCE|Dracula'],
  ['Meet Joe Black',                        1998, 'ROMANCE|Meet Joe Black'],
  ['The Parent Trap',                       1998, 'ROMANCE|The Parent Trap'],
  ['My Girl',                               1991, 'ROMANCE|My Girl'],
  ['Aladdin',                               1992, 'ROMANCE|Aladdin'],
  ['The Last of the Mohicans',              1992, 'ROMANCE|The Last of the Mohicans'],
  ['As Good as It Gets',                    1997, 'ROMANCE|As Good as It Gets'],
  ['The Virgin Suicides',                   1999, 'ROMANCE|The Virgin Suicides'],
  ['The Thomas Crown Affair',               1999, 'ROMANCE|The Thomas Crown Affair'],
  ['Four Weddings and a Funeral',           1994, 'ROMANCE|Four Weddings and a Funeral'],
  ["You've Got Mail",                       1998, "ROMANCE|You've Got Mail"],
  ['Beauty and the Beast',                  1991, 'ROMANCE|Beauty and the Beast'],
  ['Groundhog Day',                         1993, 'ROMANCE|Groundhog Day'],
  ['Lolita',                                1997, 'ROMANCE|Lolita'],
  ['Empire Records',                        1995, 'ROMANCE|Empire Records'],
  ['Sleepless in Seattle',                  1993, 'ROMANCE|Sleepless in Seattle'],
  ['Edward Scissorhands',                   1990, 'ROMANCE|Edward Scissorhands'],
  ['Robin Hood Prince of Thieves',          1991, 'ROMANCE|Robin Hood: Prince of Thieves'],
  ['Chungking Express',                     1994, 'ROMANCE|Chungking Express'],
  ['Natural Born Killers',                  1994, 'ROMANCE|Natural Born Killers'],
  ['The Bodyguard',                         1992, 'ROMANCE|The Bodyguard'],
  ['The English Patient',                   1996, 'ROMANCE|The English Patient'],
  ['The Quick and the Dead',                1995, 'ROMANCE|The Quick and the Dead'],
  ['The Cider House Rules',                 1999, 'ROMANCE|The Cider House Rules'],
  ['Anastasia',                             1997, 'ROMANCE|Anastasia'],
  ['Buffalo 66',                            1998, "ROMANCE|Buffalo '66"],
  ['Indecent Proposal',                     1993, 'ROMANCE|Indecent Proposal'],
  ['The Mask of Zorro',                     1998, 'ROMANCE|The Mask of Zorro'],
  ['Robin Hood Men in Tights',              1993, 'ROMANCE|Robin Hood: Men in Tights'],
  ['Leaving Las Vegas',                     1995, 'ROMANCE|Leaving Las Vegas'],
  ['Patch Adams',                           1998, 'ROMANCE|Patch Adams'],
  ['What Dreams May Come',                  1998, 'ROMANCE|What Dreams May Come'],
  ['Father of the Bride',                   1991, 'ROMANCE|Father of the Bride'],
  ['Pocahontas',                            1995, 'ROMANCE|Pocahontas'],
  ["She's All That",                        1999, "ROMANCE|She's All That"],
  ['Out of Sight',                          1998, 'ROMANCE|Out of Sight'],
  ["My Best Friend's Wedding",              1997, "ROMANCE|My Best Friend's Wedding"],
  ['The Age of Innocence',                  1993, 'ROMANCE|The Age of Innocence'],
  ['Ever After',                            1998, 'ROMANCE|Ever After'],
  ['Sliding Doors',                         1998, 'ROMANCE|Sliding Doors'],
  ['Fallen Angels',                         1995, 'ROMANCE|Fallen Angels'],
  ['Much Ado About Nothing',                1993, 'ROMANCE|Much Ado About Nothing'],
  ['While You Were Sleeping',               1995, 'ROMANCE|While You Were Sleeping'],
  ['Message in a Bottle',                   1999, 'ROMANCE|Message in a Bottle'],
  ['Chasing Amy',                           1997, 'ROMANCE|Chasing Amy'],
  ['The Crying Game',                       1992, 'ROMANCE|The Crying Game'],
  ['Little Women',                          1994, 'ROMANCE|Little Women'],
  ['City of Angels',                        1998, 'ROMANCE|City of Angels'],
  ['The Bridges of Madison County',         1995, 'ROMANCE|The Bridges of Madison County'],
  ['Shakespeare in Love',                   1998, 'ROMANCE|Shakespeare in Love'],
  ['Rushmore',                              1998, 'ROMANCE|Rushmore'],
  ['Whisper of the Heart',                  1995, 'ROMANCE|Whisper of the Heart'],
  ['Three Colors Blue',                     1993, 'ROMANCE|Three Colors: Blue'],
  ['The Remains of the Day',                1993, 'ROMANCE|The Remains of the Day'],
  ['Happy Together',                        1997, 'ROMANCE|Happy Together'],
  ["Boys Don't Cry",                        1999, "ROMANCE|Boys Don't Cry"],
  ['Three Colors Red',                      1994, 'ROMANCE|Three Colors: Red'],
  ['Farewell My Concubine',                 1993, 'ROMANCE|Farewell My Concubine'],
  ['Grosse Pointe Blank',                   1997, 'ROMANCE|Grosse Pointe Blank'],
  ['Runaway Bride',                         1999, 'ROMANCE|Runaway Bride'],
  ['The Piano',                             1993, 'ROMANCE|The Piano'],
  ['Benny and Joon',                        1993, 'ROMANCE|Benny & Joon'],
  ['Raise the Red Lantern',                 1991, 'ROMANCE|Raise the Red Lantern'],
  ['The Legend of 1900',                    1998, 'ROMANCE|The Legend of 1900'],
  ['French Kiss',                           1995, 'ROMANCE|French Kiss'],
  ['Dilwale Dulhania Le Jayenge',           1995, 'ROMANCE|Dilwale Dulhania Le Jayenge'],
  ['The American President',                1995, 'ROMANCE|The American President'],
  ['Days of Being Wild',                    1990, 'ROMANCE|Days of Being Wild'],
  ['Reality Bites',                         1994, 'ROMANCE|Reality Bites'],
  ['The Double Life of Veronique',          1991, 'ROMANCE|The Double Life of Véronique'],
  ['It Could Happen to You',                1994, 'ROMANCE|It Could Happen to You'],
  ['Never Been Kissed',                     1999, 'ROMANCE|Never Been Kissed'],
  ['Blast from the Past',                   1999, 'ROMANCE|Blast from the Past'],
  ['The Hunchback of Notre Dame',           1996, 'ROMANCE|The Hunchback of Notre Dame'],
  ['Now and Then',                          1995, 'ROMANCE|Now and Then'],
  ['Three Colors White',                    1994, 'ROMANCE|Three Colors: White'],
  ['Only Yesterday',                        1991, 'ROMANCE|Only Yesterday'],
  ['Fireworks',                             1997, 'ROMANCE|Fireworks'],
  ['A Brighter Summer Day',                 1991, 'ROMANCE|A Brighter Summer Day'],
  ['The Man in the Moon',                   1991, 'ROMANCE|The Man in the Moon'],
  ['Immortal Beloved',                      1994, 'ROMANCE|Immortal Beloved'],
  ['The Lovers on the Bridge',              1991, 'ROMANCE|The Lovers on the Bridge'],

  // ── 2000s Horror ────────────────────────────────────────────────────────────
  ['28 Days Later',                         2002, 'HORROR2000|28 Days Later'],
  ['American Psycho',                       2000, 'HORROR2000|American Psycho'],
  ['28 Weeks Later',                        2007, 'HORROR2000|28 Weeks Later'],
  ['Resident Evil',                         2002, 'HORROR2000|Resident Evil'],
  ['The Others',                            2001, 'HORROR2000|The Others'],
  ['The Descent',                           2005, 'HORROR2000|The Descent'],
  ['Saw',                                   2004, 'HORROR2000|Saw'],
  ['Constantine',                           2005, 'HORROR2000|Constantine'],
  ['Shaun of the Dead',                     2004, 'HORROR2000|Shaun of the Dead'],
  ['Silent Hill',                           2006, 'HORROR2000|Silent Hill'],
  ['The Mist',                              2007, 'HORROR2000|The Mist'],
  ['Zombieland',                            2009, 'HORROR2000|Zombieland'],
  ["Jennifer's Body",                       2009, "HORROR2000|Jennifer's Body"],
  ['Final Destination',                     2000, 'HORROR2000|Final Destination'],
  ['Martyrs',                               2008, 'HORROR2000|Martyrs'],
  ['I Am Legend',                           2007, 'HORROR2000|I Am Legend'],
  ['Cloverfield',                           2008, 'HORROR2000|Cloverfield'],
  ['REC',                                   2007, 'HORROR2000|[REC]'],
  ['Hostel',                                2005, 'HORROR2000|Hostel'],
  ['Let the Right One In',                  2008, 'HORROR2000|Let the Right One In'],
  ['Dawn of the Dead',                      2004, 'HORROR2000|Dawn of the Dead'],
  ['The Ring',                              2002, 'HORROR2000|The Ring'],
  ['Sweeney Todd The Demon Barber',         2007, 'HORROR2000|Sweeney Todd'],
  ['Hellboy',                               2004, 'HORROR2000|Hellboy'],
  ['The Strangers',                         2008, 'HORROR2000|The Strangers'],
  ['Jeepers Creepers',                      2001, 'HORROR2000|Jeepers Creepers'],
  ['1408',                                  2007, 'HORROR2000|1408'],
  ['The Hills Have Eyes',                   2006, 'HORROR2000|The Hills Have Eyes'],
  ['Drag Me to Hell',                       2009, 'HORROR2000|Drag Me to Hell'],
  ['The Host',                              2006, 'HORROR2000|The Host'],
  ['Quarantine',                            2008, 'HORROR2000|Quarantine'],
  ['Paranormal Activity',                   2007, 'HORROR2000|Paranormal Activity'],
  ["The Devil's Backbone",                  2001, "HORROR2000|The Devil's Backbone"],
  ['High Tension',                          2003, 'HORROR2000|High Tension'],
  ['Grindhouse',                            2007, 'HORROR2000|Grindhouse'],
  ['Wolf Creek',                            2005, 'HORROR2000|Wolf Creek'],
  ['The Texas Chainsaw Massacre',           2003, 'HORROR2000|The Texas Chainsaw Massacre'],
  ['The Loved Ones',                        2009, 'HORROR2000|The Loved Ones'],
  ["The Devil's Rejects",                   2005, "HORROR2000|The Devil's Rejects"],
  ['House of 1000 Corpses',                 2003, 'HORROR2000|House of 1000 Corpses'],
  ['Ginger Snaps',                          2000, 'HORROR2000|Ginger Snaps'],
  ['Saw II',                                2005, 'HORROR2000|Saw II'],
  ['The Grudge',                            2004, 'HORROR2000|The Grudge'],
  ['Session 9',                             2001, 'HORROR2000|Session 9'],
  ['The Exorcism of Emily Rose',            2005, 'HORROR2000|The Exorcism of Emily Rose'],
  ['The Orphanage',                         2007, 'HORROR2000|The Orphanage'],
  ['Friday the 13th',                       2009, 'HORROR2000|Friday the 13th'],
  ['A Tale of Two Sisters',                 2003, 'HORROR2000|A Tale of Two Sisters'],
  ['Thirst',                                2009, 'HORROR2000|Thirst'],
  ['Pitch Black',                           2000, 'HORROR2000|Pitch Black'],
  ['Eden Lake',                             2008, 'HORROR2000|Eden Lake'],
  ['Wrong Turn',                            2003, 'HORROR2000|Wrong Turn'],
  ['30 Days of Night',                      2007, 'HORROR2000|30 Days of Night'],
  ['Shadow of the Vampire',                 2000, 'HORROR2000|Shadow of the Vampire'],
  ['Daybreakers',                           2009, 'HORROR2000|Daybreakers'],
  ['Halloween',                             2007, 'HORROR2000|Halloween'],
  ['Orphan',                                2009, 'HORROR2000|Orphan'],
  ['Bubba Ho-Tep',                          2002, 'HORROR2000|Bubba Ho-Tep'],
  ['Dead Snow',                             2009, 'HORROR2000|Dead Snow'],
  ['Brotherhood of the Wolf',               2001, 'HORROR2000|Brotherhood of the Wolf'],
  ['The Gift',                              2000, 'HORROR2000|The Gift'],
  ['Pandorum',                              2009, 'HORROR2000|Pandorum'],
  ['What Lies Beneath',                     2000, 'HORROR2000|What Lies Beneath'],
  ['Freddy vs Jason',                       2003, 'HORROR2000|Freddy vs. Jason'],
  ['From Hell',                             2001, 'HORROR2000|From Hell'],
  ['Cabin Fever',                           2002, 'HORROR2000|Cabin Fever'],

  // ── '80s Horror ──────────────────────────────────────────────────────────────
  ['The Shining',                           1980, 'HORROR80|The Shining'],
  ['The Thing',                             1982, 'HORROR80|The Thing'],
  ['Aliens',                                1986, 'HORROR80|Aliens'],
  ['Predator',                              1987, 'HORROR80|Predator'],
  ['The Lost Boys',                         1987, 'HORROR80|The Lost Boys'],
  ['The Evil Dead',                         1981, 'HORROR80|The Evil Dead'],
  ['They Live',                             1988, 'HORROR80|They Live'],
  ['A Nightmare on Elm Street',             1984, 'HORROR80|A Nightmare on Elm Street'],
  ['Little Shop of Horrors',                1986, 'HORROR80|Little Shop of Horrors'],
  ['Poltergeist',                           1982, 'HORROR80|Poltergeist'],
  ['The Fly',                               1986, 'HORROR80|The Fly'],
  ['Angel Heart',                           1987, 'HORROR80|Angel Heart'],
  ['Gremlins',                              1984, 'HORROR80|Gremlins'],
  ['An American Werewolf in London',        1981, 'HORROR80|An American Werewolf in London'],
  ["Child's Play",                          1988, "HORROR80|Child's Play"],
  ['Friday the 13th',                       1980, 'HORROR80|Friday the 13th'],
  ['Evil Dead II',                          1987, 'HORROR80|Evil Dead II'],
  ['Videodrome',                            1983, 'HORROR80|Videodrome'],
  ['Hellraiser',                            1987, 'HORROR80|Hellraiser'],
  ['Pet Sematary',                          1989, 'HORROR80|Pet Sematary'],
  ['The Witches of Eastwick',               1987, 'HORROR80|The Witches of Eastwick'],
  ['Christine',                             1983, 'HORROR80|Christine'],
  ['Near Dark',                             1987, 'HORROR80|Near Dark'],
  ['Fright Night',                          1985, 'HORROR80|Fright Night'],
  ['The Fog',                               1980, 'HORROR80|The Fog'],
  ['Dead Ringers',                          1988, 'HORROR80|Dead Ringers'],
  ['The Return of the Living Dead',         1985, 'HORROR80|The Return of the Living Dead'],
  ['Killer Klowns from Outer Space',        1988, 'HORROR80|Killer Klowns from Outer Space'],
  ['Scanners',                              1981, 'HORROR80|Scanners'],
  ['Re-Animator',                           1985, 'HORROR80|Re-Animator'],
  ['Creepshow',                             1982, 'HORROR80|Creepshow'],
  ['Day of the Dead',                       1985, 'HORROR80|Day of the Dead'],
  ['Dead Calm',                             1989, 'HORROR80|Dead Calm'],
  ['Halloween II',                          1981, 'HORROR80|Halloween II'],
  ['Possession',                            1981, 'HORROR80|Possession'],
  ['Altered States',                        1980, 'HORROR80|Altered States'],
  ['The Changeling',                        1980, 'HORROR80|The Changeling'],
  ['The Monster Squad',                     1987, 'HORROR80|The Monster Squad'],
  ['From Beyond',                           1986, 'HORROR80|From Beyond'],
  ['Cat People',                            1982, 'HORROR80|Cat People'],
  ['The Hunger',                            1983, 'HORROR80|The Hunger'],
  ['The Howling',                           1981, 'HORROR80|The Howling'],
  ['Children of the Corn',                  1984, 'HORROR80|Children of the Corn'],
  ['Silver Bullet',                         1985, 'HORROR80|Silver Bullet'],
  ['The Blob',                              1988, 'HORROR80|The Blob'],
  ['Cujo',                                  1983, 'HORROR80|Cujo'],
  ['Prince of Darkness',                    1987, 'HORROR80|Prince of Darkness'],
  ['Tenebrae',                              1982, 'HORROR80|Tenebrae'],
  ['The Company of Wolves',                 1984, 'HORROR80|The Company of Wolves'],

  // ── Oscar Winners ─────────────────────────────────────────────────────────
  ['Sinners',                               2025, 'OSCAR|Sinners'],
  ['Anora',                                 2024, 'OSCAR|Anora'],
  ['The Brutalist',                         2024, 'OSCAR|The Brutalist'],
  ['Emilia Perez',                          2024, 'OSCAR|Emilia Pérez'],
  ['Wicked',                                2024, 'OSCAR|Wicked'],
  ['Dune Part Two',                         2024, 'OSCAR|Dune: Part Two'],
  ['Conclave',                              2024, 'OSCAR|Conclave'],
  ['Flow',                                  2024, 'OSCAR|Flow'],
  ['Oppenheimer',                           2023, 'OSCAR|Oppenheimer'],
  ['Poor Things',                           2023, 'OSCAR|Poor Things'],
  ['The Zone of Interest',                  2023, 'OSCAR|The Zone of Interest'],
  ['Barbie',                                2023, 'OSCAR|Barbie'],
  ['The Holdovers',                         2023, 'OSCAR|The Holdovers'],
  ['American Fiction',                      2023, 'OSCAR|American Fiction'],
  ['Anatomy of a Fall',                     2023, 'OSCAR|Anatomy of a Fall'],
  ['Everything Everywhere All at Once',     2022, 'OSCAR|Everything Everywhere All at Once'],
  ['All Quiet on the Western Front',        2022, 'OSCAR|All Quiet on the Western Front'],
  ['Avatar The Way of Water',               2022, 'OSCAR|Avatar: The Way of Water'],
  ['Top Gun Maverick',                      2022, 'OSCAR|Top Gun: Maverick'],
  ['Black Panther Wakanda Forever',         2022, 'OSCAR|Black Panther: Wakanda Forever'],
  ['The Whale',                             2022, 'OSCAR|The Whale'],
  ['Women Talking',                         2022, 'OSCAR|Women Talking'],
  ['CODA',                                  2021, 'OSCAR|CODA'],
  ['Dune',                                  2021, 'OSCAR|Dune'],
  ['The Eyes of Tammy Faye',                2021, 'OSCAR|The Eyes of Tammy Faye'],
  ['Encanto',                               2021, 'OSCAR|Encanto'],
  ['No Time to Die',                        2021, 'OSCAR|No Time to Die'],
  ['Drive My Car',                          2021, 'OSCAR|Drive My Car'],
  ['West Side Story',                       2021, 'OSCAR|West Side Story'],
  ['The Power of the Dog',                  2021, 'OSCAR|The Power of the Dog'],
  ['King Richard',                          2021, 'OSCAR|King Richard'],
  ['Nomadland',                             2020, 'OSCAR|Nomadland'],
  ['The Father',                            2020, 'OSCAR|The Father'],
  ['Judas and the Black Messiah',           2020, 'OSCAR|Judas and the Black Messiah'],
  ['Sound of Metal',                        2020, 'OSCAR|Sound of Metal'],
  ["Ma Rainey's Black Bottom",              2020, "OSCAR|Ma Rainey's Black Bottom"],
  ['Promising Young Woman',                 2020, 'OSCAR|Promising Young Woman'],
  ['Soul',                                  2020, 'OSCAR|Soul'],
  ['Another Round',                         2020, 'OSCAR|Another Round'],
  ['Minari',                                2020, 'OSCAR|Minari'],
  ['Parasite',                              2019, 'OSCAR|Parasite'],
  ['Ford v Ferrari',                        2019, 'OSCAR|Ford v Ferrari'],
  ['Jojo Rabbit',                           2019, 'OSCAR|Jojo Rabbit'],
  ['Little Women',                          2019, 'OSCAR|Little Women'],
  ['Marriage Story',                        2019, 'OSCAR|Marriage Story'],
  ['Toy Story 4',                           2019, 'OSCAR|Toy Story 4'],
  ['Joker',                                 2019, 'OSCAR|Joker'],
  ['Once Upon a Time in Hollywood',         2019, 'OSCAR|Once Upon a Time in Hollywood'],
  ['1917',                                  2019, 'OSCAR|1917'],
  ['Judy',                                  2019, 'OSCAR|Judy'],
  ['Green Book',                            2018, 'OSCAR|Green Book'],
  ['Bohemian Rhapsody',                     2018, 'OSCAR|Bohemian Rhapsody'],
  ['Roma',                                  2018, 'OSCAR|Roma'],
  ['Black Panther',                         2018, 'OSCAR|Black Panther'],
  ['The Favourite',                         2018, 'OSCAR|The Favourite'],
  ['A Star Is Born',                        2018, 'OSCAR|A Star Is Born'],
  ['BlacKkKlansman',                        2018, 'OSCAR|BlacKkKlansman'],
  ['Spider-Man Into the Spider-Verse',      2018, 'OSCAR|Spider-Man: Into the Spider-Verse'],
  ['If Beale Street Could Talk',            2018, 'OSCAR|If Beale Street Could Talk'],
  ['The Shape of Water',                    2017, 'OSCAR|The Shape of Water'],
  ['Dunkirk',                               2017, 'OSCAR|Dunkirk'],
  ['Three Billboards Outside Ebbing Missouri', 2017, 'OSCAR|Three Billboards Outside Ebbing, Missouri'],
  ['Darkest Hour',                          2017, 'OSCAR|Darkest Hour'],
  ['Blade Runner 2049',                     2017, 'OSCAR|Blade Runner 2049'],
  ['Coco',                                  2017, 'OSCAR|Coco'],
  ['Call Me by Your Name',                  2017, 'OSCAR|Call Me by Your Name'],
  ['Get Out',                               2017, 'OSCAR|Get Out'],
  ['Moonlight',                             2016, 'OSCAR|Moonlight'],
  ['La La Land',                            2016, 'OSCAR|La La Land'],
  ['Hacksaw Ridge',                         2016, 'OSCAR|Hacksaw Ridge'],
  ['Manchester by the Sea',                 2016, 'OSCAR|Manchester by the Sea'],
  ['Arrival',                               2016, 'OSCAR|Arrival'],
  ['Fences',                                2016, 'OSCAR|Fences'],
  ['Zootopia',                              2016, 'OSCAR|Zootopia'],
  ['Spotlight',                             2015, 'OSCAR|Spotlight'],
  ['Mad Max Fury Road',                     2015, 'OSCAR|Mad Max: Fury Road'],
  ['The Revenant',                          2015, 'OSCAR|The Revenant'],
  ['Room',                                  2015, 'OSCAR|Room'],
  ['The Big Short',                         2015, 'OSCAR|The Big Short'],
  ['Inside Out',                            2015, 'OSCAR|Inside Out'],
  ['Ex Machina',                            2015, 'OSCAR|Ex Machina'],
  ['Birdman',                               2014, 'OSCAR|Birdman'],
  ['The Grand Budapest Hotel',              2014, 'OSCAR|The Grand Budapest Hotel'],
  ['Whiplash',                              2014, 'OSCAR|Whiplash'],
  ['The Imitation Game',                    2014, 'OSCAR|The Imitation Game'],
  ['Interstellar',                          2014, 'OSCAR|Interstellar'],
  ['The Theory of Everything',              2014, 'OSCAR|The Theory of Everything'],
  ['Selma',                                 2014, 'OSCAR|Selma'],
  ['Still Alice',                           2014, 'OSCAR|Still Alice'],
  ['12 Years a Slave',                      2013, 'OSCAR|12 Years a Slave'],
  ['Gravity',                               2013, 'OSCAR|Gravity'],
  ['Dallas Buyers Club',                    2013, 'OSCAR|Dallas Buyers Club'],
  ['Frozen',                                2013, 'OSCAR|Frozen'],
  ['Her',                                   2013, 'OSCAR|Her'],
  ['Blue Jasmine',                          2013, 'OSCAR|Blue Jasmine'],
  ['Argo',                                  2012, 'OSCAR|Argo'],
  ['Life of Pi',                            2012, 'OSCAR|Life of Pi'],
  ['Les Miserables',                        2012, 'OSCAR|Les Misérables'],
  ['Lincoln',                               2012, 'OSCAR|Lincoln'],
  ['Django Unchained',                      2012, 'OSCAR|Django Unchained'],
  ['Skyfall',                               2012, 'OSCAR|Skyfall'],
  ['Silver Linings Playbook',               2012, 'OSCAR|Silver Linings Playbook'],
  ['Brave',                                 2012, 'OSCAR|Brave'],
  ['Amour',                                 2012, 'OSCAR|Amour'],
  ['The Artist',                            2011, 'OSCAR|The Artist'],
  ['Hugo',                                  2011, 'OSCAR|Hugo'],
  ['The Iron Lady',                         2011, 'OSCAR|The Iron Lady'],
  ['The Descendants',                       2011, 'OSCAR|The Descendants'],
  ['Midnight in Paris',                     2011, 'OSCAR|Midnight in Paris'],
  ['A Separation',                          2011, 'OSCAR|A Separation'],
  ['Rango',                                 2011, 'OSCAR|Rango'],
  ["The King's Speech",                     2010, "OSCAR|The King's Speech"],
  ['Inception',                             2010, 'OSCAR|Inception'],
  ['Toy Story 3',                           2010, 'OSCAR|Toy Story 3'],
  ['Black Swan',                            2010, 'OSCAR|Black Swan'],
  ['Alice in Wonderland',                   2010, 'OSCAR|Alice in Wonderland'],
  ['The Hurt Locker',                       2009, 'OSCAR|The Hurt Locker'],
  ['Avatar',                                2009, 'OSCAR|Avatar'],
  ['Precious',                              2009, 'OSCAR|Precious'],
  ['Up',                                    2009, 'OSCAR|Up'],
  ['Inglourious Basterds',                  2009, 'OSCAR|Inglourious Basterds'],
  ['Slumdog Millionaire',                   2008, 'OSCAR|Slumdog Millionaire'],
  ['The Dark Knight',                       2008, 'OSCAR|The Dark Knight'],
  ['WALL-E',                                2008, 'OSCAR|WALL-E'],
  ['Milk',                                  2008, 'OSCAR|Milk'],
  ['Vicky Cristina Barcelona',              2008, 'OSCAR|Vicky Cristina Barcelona'],
  ['Departures',                            2008, 'OSCAR|Departures'],
  ['No Country for Old Men',                2007, 'OSCAR|No Country for Old Men'],
  ['There Will Be Blood',                   2007, 'OSCAR|There Will Be Blood'],
  ['Ratatouille',                           2007, 'OSCAR|Ratatouille'],
  ['Juno',                                  2007, 'OSCAR|Juno'],
  ['Atonement',                             2007, 'OSCAR|Atonement'],
  ['Once',                                  2007, 'OSCAR|Once'],
  ['The Departed',                          2006, 'OSCAR|The Departed'],
  ["Pan's Labyrinth",                       2006, "OSCAR|Pan's Labyrinth"],
  ['Little Miss Sunshine',                  2006, 'OSCAR|Little Miss Sunshine'],
  ['Babel',                                 2006, 'OSCAR|Babel'],
  ['Happy Feet',                            2006, 'OSCAR|Happy Feet'],
  ['Crash',                                 2005, 'OSCAR|Crash'],
  ['Brokeback Mountain',                    2005, 'OSCAR|Brokeback Mountain'],
  ['Capote',                                2005, 'OSCAR|Capote'],
  ['Syriana',                               2005, 'OSCAR|Syriana'],
  ['Walk the Line',                         2005, 'OSCAR|Walk the Line'],
  ['Wallace and Gromit Curse of the Were-Rabbit', 2005, 'OSCAR|Wallace & Gromit: The Curse of the Were-Rabbit'],
  ['Million Dollar Baby',                   2004, 'OSCAR|Million Dollar Baby'],
  ['Ray',                                   2004, 'OSCAR|Ray'],
  ['Sideways',                              2004, 'OSCAR|Sideways'],
  ['Eternal Sunshine of the Spotless Mind', 2004, 'OSCAR|Eternal Sunshine of the Spotless Mind'],
  ['Spider-Man 2',                          2004, 'OSCAR|Spider-Man 2'],
  ['Chicago',                               2002, 'OSCAR|Chicago'],
  ['The Lord of the Rings The Two Towers',  2002, 'OSCAR|The Lord of the Rings: The Two Towers'],
  ['Frida',                                 2002, 'OSCAR|Frida'],
  ['Adaptation',                            2002, 'OSCAR|Adaptation'],
  ['Spirited Away',                         2002, 'OSCAR|Spirited Away'],
  ['8 Mile',                                2002, 'OSCAR|8 Mile'],
  ['A Beautiful Mind',                      2001, 'OSCAR|A Beautiful Mind'],
  ['The Lord of the Rings Fellowship of the Ring', 2001, 'OSCAR|The Lord of the Rings: The Fellowship of the Ring'],
  ['Moulin Rouge',                          2001, 'OSCAR|Moulin Rouge!'],
  ['Black Hawk Down',                       2001, 'OSCAR|Black Hawk Down'],
  ['Shrek',                                 2001, 'OSCAR|Shrek'],
  ['Training Day',                          2001, 'OSCAR|Training Day'],
  ["Monster's Ball",                        2001, "OSCAR|Monster's Ball"],
  ['Gladiator',                             2000, 'OSCAR|Gladiator'],
  ['Crouching Tiger Hidden Dragon',         2000, 'OSCAR|Crouching Tiger, Hidden Dragon'],
  ['Traffic',                               2000, 'OSCAR|Traffic'],
  ['Erin Brockovich',                       2000, 'OSCAR|Erin Brockovich'],
  ['Almost Famous',                         2000, 'OSCAR|Almost Famous'],
  ['American Beauty',                       1999, 'OSCAR|American Beauty'],
  ["Boys Don't Cry",                        1999, "OSCAR|Boys Don't Cry"],
  ['Shakespeare in Love',                   1998, 'OSCAR|Shakespeare in Love'],
  ['Saving Private Ryan',                   1998, 'OSCAR|Saving Private Ryan'],
  ['Life Is Beautiful',                     1998, 'OSCAR|Life Is Beautiful'],
  ['Gods and Monsters',                     1998, 'OSCAR|Gods and Monsters'],
  ['Titanic',                               1997, 'OSCAR|Titanic'],
  ['Good Will Hunting',                     1997, 'OSCAR|Good Will Hunting'],
  ['L.A. Confidential',                     1997, 'OSCAR|L.A. Confidential'],
  ['As Good as It Gets',                    1997, 'OSCAR|As Good as It Gets'],
  ['Men in Black',                          1997, 'OSCAR|Men in Black'],
  ['The English Patient',                   1996, 'OSCAR|The English Patient'],
  ['Fargo',                                 1996, 'OSCAR|Fargo'],
  ['Jerry Maguire',                         1996, 'OSCAR|Jerry Maguire'],
  ['Shine',                                 1996, 'OSCAR|Shine'],
  ['Braveheart',                            1995, 'OSCAR|Braveheart'],
  ['Leaving Las Vegas',                     1995, 'OSCAR|Leaving Las Vegas'],
  ['Apollo 13',                             1995, 'OSCAR|Apollo 13'],
  ['Babe',                                  1995, 'OSCAR|Babe'],
  ['Forrest Gump',                          1994, 'OSCAR|Forrest Gump'],
  ['Pulp Fiction',                          1994, 'OSCAR|Pulp Fiction'],
  ['Ed Wood',                               1994, 'OSCAR|Ed Wood'],
  ['Speed',                                 1994, 'OSCAR|Speed'],
  ['The Lion King',                         1994, 'OSCAR|The Lion King'],
  ["Schindler's List",                      1993, "OSCAR|Schindler's List"],
  ['The Fugitive',                          1993, 'OSCAR|The Fugitive'],
  ['Mrs Doubtfire',                         1993, "OSCAR|Mrs. Doubtfire"],
  ['The Piano',                             1993, 'OSCAR|The Piano'],
  ['Philadelphia',                          1993, 'OSCAR|Philadelphia'],
  ['Unforgiven',                            1992, 'OSCAR|Unforgiven'],
  ['Scent of a Woman',                      1992, 'OSCAR|Scent of a Woman'],
  ['The Crying Game',                       1992, 'OSCAR|The Crying Game'],
  ['Aladdin',                               1992, 'OSCAR|Aladdin'],
  ['The Silence of the Lambs',              1991, 'OSCAR|The Silence of the Lambs'],
  ['JFK',                                   1991, 'OSCAR|JFK'],
  ['Beauty and the Beast',                  1991, 'OSCAR|Beauty and the Beast'],
  ['Terminator 2 Judgment Day',             1991, 'OSCAR|Terminator 2: Judgment Day'],
  ['Dances with Wolves',                    1990, 'OSCAR|Dances with Wolves'],
  ['GoodFellas',                            1990, 'OSCAR|GoodFellas'],
  ['Ghost',                                 1990, 'OSCAR|Ghost'],
  ['Total Recall',                          1990, 'OSCAR|Total Recall'],
  ['Dick Tracy',                            1990, 'OSCAR|Dick Tracy'],
  ['The Lord of the Rings Return of the King', 2003, 'OSCAR|The Lord of the Rings: The Return of the King'],
];

async function lookup(title, year, label) {
  const url = 'https://api.themoviedb.org/3/search/movie?query=' +
    encodeURIComponent(title) + '&year=' + year + '&language=en-US';
  const res = await fetch(url, {
    headers: { Authorization: 'Bearer ' + TOKEN }
  });
  const data = await res.json();
  const top = data.results?.[0];
  if (top) {
    console.log(label + '\t' + top.id + '\t' + top.title + '\t' + (top.release_date?.slice(0, 4) ?? '?'));
  } else {
    // Retry without year
    const url2 = 'https://api.themoviedb.org/3/search/movie?query=' +
      encodeURIComponent(title) + '&language=en-US';
    const res2 = await fetch(url2, { headers: { Authorization: 'Bearer ' + TOKEN } });
    const data2 = await res2.json();
    const top2 = data2.results?.[0];
    if (top2) {
      console.log(label + '\t' + top2.id + '\t' + top2.title + '\t' + (top2.release_date?.slice(0, 4) ?? '?') + '\t(no-year)');
    } else {
      console.log(label + '\tNOT_FOUND\t' + title + '\t' + year);
    }
  }
}

for (const [title, year, label] of films) {
  await lookup(title, year, label);
  await new Promise(r => setTimeout(r, 150));
}
